models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  Copyright 2018 Joshua <ogunyinkajoshua@gmail.com>

import os

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
DEFAULT_DISPLAY_PICTURE = os.environ.get('DEFAULT_DP')


class ContactMessage(db.Model):
    __tablename__ = 'contact_messages'

    id = db.Column(db.Integer, primary_key=True, index=True)
    fullname = db.Column(db.String(128), nullable=False)
    email = db.Column(db.String( 128 ), nullable = False, index = True)
    subject = db.Column(db.String(256), nullable=False)
    message = db.Column(db.Text, nullable=True)
    
    def __repr__(self):
        return '<ContactMessages Name: {}, Message: {}>\n'.format(self.fullname, self.message)

    
class Article(db.Model):
    __tablename__ = 'articles'
    id = db.Column(db.Integer, primary_key=True, index=True, unique=True)
    topic = db.Column(db.String(256), nullable=False, unique=True)
    categories = db.Column(db.String(512), nullable=False)
    writer = db.Column(db.String(128), nullable=False)
    date_written = db.Column(db.DateTime, nullable=False)
    brief = db.Column(db.Text, nullable=False)
    blog_filename = db.Column(db.String(512), nullable=False, unique=True)
    comments = db.relationship('Comment', backref='user_comments')
    
    @staticmethod
    def get_articles(articles_object):
        if articles_object is None: return []
        return [ { 'topic': article.topic, 'date': article.date_written,\
            'writer': article.writer, 'comments': len(article.comments),\
            'category': article.categories, 'topic_id': article.id,\
            'brief': article.brief } for article in articles_object ]
    
    @staticmethod
    def get_comments(comments):
        if len(comments) == 0: return [] 
        return [ {'name': comment.commenter_name, 'comment': comment.comment_text,\
            'replies': get_comments(comment.replies)} for comment in comments]

    @staticmethod
    def get_single_article(article):
        if article is None: return article
        date_written = article.date_written.strftime('%b %d, %Y')
        return { 'topic': article.topic, 'date': date_written, 'writer': article.writer,\
            'comments': Article.get_comments(article.comments), 'category': article.categories,\
            'num_comment': len(article.comments) }


class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True, index=True)
    commenter_name = db.Column(db.String(256), nullable=False)
    commenter_email = db.Column(db.String(256), nullable=False)
    comment_text = db.Column(db.Text, nullable=False)
    article_id = db.Column(db.Integer, db.ForeignKey('articles.id'))
    replies = db.relationship('Comment')
    response_id = db.Column(db.Integer, db.ForeignKey('comments.id'))

views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  Copyright 2018 Joshua <ogunyinkajoshua@gmail.com>
import json
import os
import redis
from logging import log

from flask import Blueprint, render_template, url_for, redirect, request, abort, flash
from flask_wtf.csrf import CSRFError
from sqlalchemy.exc import IntegrityError

from models import db, ContactMessage, Article

main = Blueprint('main', __name__)
cache_pass,port_number=os.environ.get('redis_pass'),int(os.environ.get('redis_port'))
instant_data_cache = redis.StrictRedis(password=cache_pass,port=port_number)
feedback = 'blog:feedback'
article_key = 'blog:article_key'


@main.errorhandler(CSRFError)
def handle_csrf_error_handler(error):
    flash(error)
    return redirect(url_for('main.index_route'))


@main.route('/home')
@main.route('/index')
@main.route('/')
def index_route():
    # get latest articles first
    all_articles = Article.get_articles(db.session.query(Article).order_by(Article.id.desc()).all())
    return render_template('index.html', articles=all_articles)


@main.route('/blog')
def blog_route():
    try:
        article_id = int(request.args.get('blog_id'))
        article_object = db.session.query(Article).filter_by(id=article_id).first()
        if article_object is None:
            return abort(404)
        article_text = instant_data_cache.hmget(article_key, article_object.blog_filename)
        if not article_text:
            article_text = ''
            with open(article.blog_filename, 'r') as text_file:
                for line in text_file:
                    article_text += line
            instant_data_cache.hmset(article_key, {article_object.blog_filename: article_text})
        else:
            if type(article_text) == list:
                article_text = article_text[0]
            article_text = article_text.decode()
        article_data = Article.get_single_article(article_object)
        return render_template('article.html', article_text=article_text, metadata=article_data)
    except ValueError as exc:
        print(exc)
        return redirect(url_for('main.index_route'))
    except Exception as exception:
        print(exception)
        return redirect(url_for('main.index_route'))


@main.route('/about_me')
def about_me_route():
    return render_template('about.html')


@main.route('/contacts', methods=['GET'])
def contacts_route():
    return render_template('contact.html')


@main.route('/receive_message', methods=['POST'])
def get_in_touch_route():
    name = request.form.get('name')
    email = request.form.get('email')
    subject = request.form.get('subject')
    message = request.form.get('message')
    
    try:
        new_message = ContactMessage(fullname=name, email=email, subject=subject, message=message)
        db.session.add(new_message)
        db.session.commit()
        cached_message = json.dumps({'name': name, 'email': email, 'subject': subject, 'message': message})
        instant_data_cache.lpush(feedback, cached_message)
        flash('Your message has been sent')
    except IntegrityError as ie:
        db.session.rollback()
        log(WARNING, ie)
        flash('There was an error sending your message')
    return redirect(url_for('main.contacts_route'))

templates/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>About(Joshua Ogunyinka)</title>

		<!-- meta -->
                <meta name="description" content="Joshua Ogunyinka">
                <link rel="shortcut icon" href="{{url_for('static', filename='favicon.ico')}}">
		<meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
            <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
            <link rel="stylesheet" href="{{url_for('static', filename='css/ionicons.min.css')}}">
            <link rel="stylesheet" href="{{url_for('static', filename='css/pace.css')}}">
            <link rel="stylesheet" href="{{url_for('static', filename='css/custom.css')}}">

	    <!-- js -->
            <script src="{{url_for('static', filename='js/jquery-2.1.3.min.js')}}"></script>
	    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
	    <script src="{{url_for('static', filename='js/pace.min.js')}}"></script>
	    <script src="{{url_for('static', filename='js/modernizr.custom.js')}}"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="{{url_for('main.index_route')}}">(un)interesting stuff</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="{{url_for('main.index_route')}}" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="#" data-hover="Projects">Projects</a></li>
    								<li class="cl-effect-11"><a href="#" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="{{url_for('main.contacts_route')}}" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="{{url_for('static', filename='img/me.jpg')}}" alt="Developer Image">
								</figure>
								<p>In a nutshell, my name is Joshua Oluwaseun Ogunyinka and I am a Nigerian. I am primarily a C++ programmer but I happen to know how to write code in Python and Java too. This website, for example, is powered by Python's Flask.
                                                                </p>
								<p>The main purpose of this website is to blog about everything I find interesting(but sometimes it may be uninteresting), and while writing about stuffs, a couple things may crop up -- ecstasy, rants, (dis)satisfactions and the in-between. My email is ogunyinkajoshua@yahoo.com, so hit me up when you have anything for me.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="https://facebook.com/iamOgunyinka"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="https://twitter.com/iamOgunyinka"><span class="ion-social-twitter"></span></a></li>
									<li class="github"><a href="https://github.com/iamOgunyinka"><span class="ion-social-github"></span></a></li>
									<li class="linkedin"><a href="https://linkedin.com/in/iamogunyinka"><span class="ion-social-linkedin"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2019 Joshua Ogunyinka</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="{{url_for('main.index_route')}}">Home</a></li>
					<li><a href="#">Projects</a></li>
					<li><a href="#">About</a></li>
					<li><a href="{{url_for('main.contacts_route')}}">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="{{url_for('static', filename='js/script.js')}}"></script>
		
	</body>
</html>

templates/article.html
<!DOCTYPE html>
<html>
        <head>
		<title> {{metadata['topic']}} </title>

		<meta name="description" content="Joshua Ogunyinka">
                <link rel="shortcut icon" href="{{url_for('static', filename='favicon.ico')}}">
		<meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
            <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
            <link rel="stylesheet" href="{{url_for('static', filename='css/ionicons.min.css')}}">
            <link rel="stylesheet" href="{{url_for('static', filename='css/pace.css')}}">
            <link rel="stylesheet" href="{{url_for('static', filename='css/custom.css')}}">
            <link rel="stylesheet" href="{{url_for('static', filename='css/code.css')}}">

	    <!-- js -->
            <script src="{{url_for('static', filename='js/jquery-2.1.3.min.js')}}"></script>
	    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
	    <script src="{{url_for('static', filename='js/pace.min.js')}}"></script>
	    <script src="{{url_for('static', filename='js/modernizr.custom.js')}}"></script>
	</head>

	<body id="single">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
                                                        <h1><a href="{{url_for('main.index_route')}}">(un)interesting stuff</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="{{url_for('main.index_route')}}" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="#" data-hover="Projects">Projects</a></li>
    								<li class="cl-effect-11"><a href="{{url_for('main.about_me_route')}}" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="{{url_for('main.contacts_route')}}" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-10">
						<article class="post post-1">
							<header class="entry-header">
								<h1 class="entry-title">{{metadata['topic']}}</h1>
								<div class="entry-meta">
									<span class="post-category"><a href="#">{{metadata['category']}}</a></span>
			
									<span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">{{metadata['date']}}</time></a></span>
			
									<span class="post-author"><a href="#">{{metadata['writer']}}</a></span>
			
									<span class="comments-link"><a href="#"> {{metadata['num_comment']}} Comment(s)</a></span>
								</div>
							</header>
							<div class="entry-content clearfix">
								{{article_text|safe}}
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2019 Joshua Ogunyinka</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="{{url_for('main.index_route')}}">Home</a></li>
					<li><a href="#">Projects</a></li>
					<li><a href="{{url_for('main.about_me_route')}}">About</a></li>
					<li><a href="{{url_for('main.contacts_route')}}">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="{{url_for('static', filename='js/script.js')}}"></script>
	</body>
</html>

templates/contact.html
<!DOCTYPE html>
<html>
	<head>
		<title>Contact(Joshua Ogunyinka)</title>

		<meta name="description" content="Joshua Ogunyinka">
                <link rel="shortcut icon" href="{{url_for('static', filename='favicon.ico')}}">
		<meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
            <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
            <link rel="stylesheet" href="{{url_for('static', filename='css/ionicons.min.css')}}">
            <link rel="stylesheet" href="{{url_for('static', filename='css/pace.css')}}">
            <link rel="stylesheet" href="{{url_for('static', filename='css/custom.css')}}">

	    <!-- js -->
            <script src="{{url_for('static', filename='js/jquery-2.1.3.min.js')}}"></script>
	    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
	    <script src="{{url_for('static', filename='js/pace.min.js')}}"></script>
	    <script src="{{url_for('static', filename='js/modernizr.custom.js')}}"></script>
	</head>


	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
                                                        <h1><a href="{{url_for('main.index_route')}}">(un)interesting stuff</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="{{url_for('main.index_route')}}" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="#" data-hover="Projects">Projects</a></li>
    								<li class="cl-effect-11"><a href="{{url_for('main.about_me_route')}}" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="#" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
                                                                {% block content %}
                                                                <div class="container">
                                                                    {% for message in get_flashed_messages() %}
                                                                    <div class="alert alert-warning">
                                                                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                                                                        {{ message }}
                                                                    </div>
                                                                    {% endfor %}
                                                                    {% block page_content %}{% endblock %}
                                                                </div>
                                                                {% endblock %}
								<form action="{{url_for('main.get_in_touch_route')}}" method="POST" class="contact-form" id="contact_form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
                                                                                        <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
											<input type="text" name="name" placeholder="Name" required>
											<input type="email" name="email" placeholder="Email" required>
											<input type="text" name="subject" placeholder="Subject" required>
											<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2019 Joshua Ogunyinka</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
                                        <li><a href="{{url_for('main.index_route')}}">Home</a></li>
					<li><a href="#">Projects</a></li>
					<li><a href="{{url_for('main.about_me_route')}}">About</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="{{url_for('static', filename='js/script.js')}}"></script>
		
	</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
	<head>
		<title>Home</title>

		<!-- meta -->
                <meta name="description" content="Joshua Ogunyinka">
                <link rel="shortcut icon" href="{{url_for('static', filename='favicon.ico')}}">
		<meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1">

                <!-- css -->
		<link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
		<link rel="stylesheet" href="{{url_for('static', filename='css/ionicons.min.css')}}">
		<link rel="stylesheet" href="{{url_for('static', filename='css/pace.css')}}">
                <link rel="stylesheet" href="{{url_for('static', filename='css/custom.css')}}">

                <!-- js -->
                <script src="{{url_for('static', filename='js/jquery-2.1.3.min.js')}}"></script>
                <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
                <script src="{{url_for('static', filename='js/pace.min.js')}}"></script>
                <script src="{{url_for('static', filename='js/modernizr.custom.js')}}"></script>
	</head>

	<body>
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="#">(un)interesting stuff</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="#" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="#" data-hover="Projects">Projects</a></li>
    								<li class="cl-effect-11"><a href="{{url_for('main.about_me_route')}}" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="{{url_for('main.contacts_route')}}" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-10">
                                        {% for article in articles %}
						<article class="post post-1">
							<header class="entry-header">
								<h1 class="entry-title">
									<a href="{{url_for('main.blog_route', blog_id=article['topic_id'])}}">{{article['topic']}}</a>
								</h1>
								<div class="entry-meta">
									<span class="post-category"><a href="#">{{article['category']}}</a></span>
			
									<span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">{{article['date']}}</time></a></span>
			
									<span class="post-author"><a href="#">{{article['writer']}}</a></span>
			
									<span class="comments-link"><a href="#">{{article['comments']}} comment(s)</a></span>
								</div>
							</header>
							<div class="entry-content clearfix">
								<p>{{article['brief']}}</p>
								<div class="read-more cl-effect-14">
									<a href="{{url_for('main.blog_route', blog_id=article['topic_id'])}}" class="more-link">Continue reading <span class="meta-nav">→</span></a>
								</div>
							</div>
						</article>
                                        {% endfor %}
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2019 Joshua Ogunyinka</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="#">Home</a></li>
					<li><a href="#">Projects</a></li>
					<li><a href="{{url_for('main.about_me_route')}}">About</a></li>
					<li><a href="{{url_for('main.contacts_route')}}">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="{{url_for('static', filename='js/script.js')}}"></script>

	</body>
</html>